export const NAME = "sidebar";

export const NEW_PAINTING = `${NAME}/NEW_PAINTING`;
export const LOAD_PAINTING = `${NAME}/LOAD_PAINTING`;
export const IMPORT_PAINTING_REQUESTED = `${NAME}/IMPORT_PAINTING_REQ`;
export const IMPORT_PAINTING_FULFILLED = `${NAME}/IMPORT_PAINTING_FUL`;